export interface GlossaryTerm {
    slug: string;
    term: string;
    letter: string;
    shortDef: string;
    definition: string;
    whyItMatters: string;
    related?: string[];
}

export const glossaryTerms: GlossaryTerm[] = [
    // # / Numeric
    { slug: "360-degree-feedback", term: "360-Degree Feedback", letter: "#", shortDef: "A performance review method that gathers input from an employee's managers, peers, subordinates, and sometimes clients.", definition: "360-degree feedback is a performance evaluation approach where an employee is assessed by everyone around them — their manager, peers, direct reports, and occasionally external stakeholders — instead of relying on a single manager's opinion. The goal is a fuller, more balanced picture of someone's strengths and blind spots.", whyItMatters: "It reduces bias from any one reviewer and surfaces feedback employees might not otherwise hear, which is why many performance management systems, including HR Niti's, support multi-rater review cycles." },

    // A
    { slug: "absconding", term: "Absconding", letter: "A", shortDef: "When an employee stops showing up to work without notice or approval and cannot be reached.", definition: "Absconding refers to an employee abandoning their job without informing the employer, submitting a resignation, or completing an exit process — often becoming unreachable in the process. It's treated differently from a normal resignation because there's no notice period served.", whyItMatters: "HR teams need a documented absconding policy to handle final settlement, recovery of company property, and compliance correctly when this happens." },
    { slug: "absent-without-leave-awol", term: "Absent Without Leave (AWOL)", letter: "A", shortDef: "An unapproved absence from work where the employee hasn't formally requested or been granted leave.", definition: "AWOL describes a situation where an employee is absent from work without prior approval and without following the organization's leave request process. It's usually flagged automatically when attendance doesn't match an approved leave record.", whyItMatters: "Automated attendance and leave systems make AWOL cases easy to spot immediately instead of discovering them at payroll time." },
    { slug: "absenteeism-policy", term: "Absenteeism Policy", letter: "A", shortDef: "A formal set of rules defining acceptable and unacceptable employee absence, and the consequences of each.", definition: "An absenteeism policy lays out how an organization defines, tracks, and responds to employee absences — including how many unplanned absences are tolerated, what documentation is required, and what disciplinary steps follow repeated violations.", whyItMatters: "A clearly configured policy in your HRMS keeps absence handling consistent across managers and locations." },
    { slug: "absolute-ratings", term: "Absolute Ratings", letter: "A", shortDef: "A performance evaluation method that rates each employee against fixed standards, not against each other.", definition: "Absolute rating methods (such as rating scales or checklists) judge an employee purely against a predefined standard of performance, unlike relative methods like the bell curve that compare employees to one another.", whyItMatters: "Choosing between absolute and relative rating methods shapes how fair — and how competitive — your performance culture feels." },
    { slug: "accrued-leave", term: "Accrued Leave", letter: "A", shortDef: "Paid leave that an employee earns gradually over time, typically based on days worked.", definition: "Accrued leave is leave balance that builds up incrementally — for example, one day of earned leave for every month worked — rather than being granted as a lump sum at the start of the year.", whyItMatters: "Automating accrual calculations avoids disputes over leave balances and keeps your leave ledger accurate without manual tracking." },
    { slug: "adhoc-allowance", term: "Adhoc Allowance", letter: "A", shortDef: "A one-time or irregular payment made outside an employee's fixed salary structure.", definition: "An adhoc allowance is a non-recurring payment given for a specific reason — such as a special project, temporary hardship, or one-off business need — rather than being part of the standard, recurring salary components.", whyItMatters: "Payroll systems need to handle these as exceptions so they don't get mistaken for a permanent change to CTC." },
    { slug: "allowance", term: "Allowance", letter: "A", shortDef: "A fixed or variable payment added to base salary to cover specific expenses or as a benefit.", definition: "An allowance is any additional payment made on top of basic salary — such as HRA, travel allowance, or medical allowance — usually intended to cover a specific category of expense or as a standard part of compensation structure.", whyItMatters: "Correct allowance configuration directly affects tax computation and statutory compliance in payroll." },
    { slug: "analytical-thinking", term: "Analytical Thinking", letter: "A", shortDef: "The ability to break down complex information and identify patterns to make sound decisions.", definition: "In an HR context, analytical thinking is a competency assessed during hiring and performance reviews — the capacity to interpret data, spot trends, and reach logical conclusions rather than relying on assumptions.", whyItMatters: "It's a common competency tracked in structured interviews and appraisal frameworks." },
    { slug: "annual-income", term: "Annual Income", letter: "A", shortDef: "The total amount an employee earns from their employer over a financial year, before or after deductions.", definition: "Annual income refers to an employee's total earnings across a year, including basic salary, allowances, bonuses, and other components — used as the basis for tax calculation and financial planning.", whyItMatters: "Accurate annual income reporting is essential for Form 16 generation and income tax filing support." },
    { slug: "applicant-tracking-system", term: "Applicant Tracking System (ATS)", letter: "A", shortDef: "Software used to manage and track candidates through the recruitment process, from application to hire.", definition: "An ATS centralizes job postings, resumes, candidate communication, and interview stages into one system, replacing manual tracking via spreadsheets or email threads.", whyItMatters: "A well-integrated ATS shortens time-to-hire and keeps recruitment data connected to onboarding once a candidate is selected.", related: ["campus-recruitment", "recruitment"] },
    { slug: "appraisal", term: "Appraisal", letter: "A", shortDef: "A formal, periodic review of an employee's job performance against set goals or standards.", definition: "A performance appraisal is a structured evaluation — usually annual or half-yearly — where a manager assesses an employee's achievements, skills, and growth areas, often tied to compensation decisions like increments or bonuses.", whyItMatters: "Automated appraisal cycles make it easier to run consistent, on-time reviews across a growing organization." },
    { slug: "apprenticeship", term: "Apprenticeship", letter: "A", shortDef: "A structured training program combining on-the-job work experience with formal instruction.", definition: "An apprenticeship is a fixed-term arrangement where a person learns a trade or skill through supervised work, often under a formal government or industry framework, in exchange for a stipend rather than a full salary.", whyItMatters: "Apprentices are usually governed by separate statutory rules than regular employees, which HR and payroll need to account for." },
    { slug: "assessment-year-ay", term: "Assessment Year (AY)", letter: "A", shortDef: "The year following the financial year in which income is assessed and taxed by the tax authorities.", definition: "The Assessment Year is the 12-month period immediately after a given Financial Year, during which the income earned in that financial year is evaluated and taxed. For example, income earned in FY 2025-26 is assessed in AY 2026-27.", whyItMatters: "Payroll and tax filing calendars are built around the distinction between the financial year and the assessment year." },
    { slug: "attendance-regularization", term: "Attendance Regularization", letter: "A", shortDef: "The process of correcting or updating an attendance record after an error, like a missed punch.", definition: "Attendance regularization lets employees request a correction to their attendance record — for instance, if they forgot to check in — subject to manager approval, so the record accurately reflects hours worked.", whyItMatters: "A smooth regularization workflow prevents payroll errors caused by minor attendance-system glitches." },

    // B
    { slug: "background-verification", term: "Background Verification", letter: "B", shortDef: "The process of confirming a candidate's employment history, education, and other claims before or after hiring.", definition: "Background verification (BGV) is the process of validating information a candidate has provided — past employment, education credentials, identity documents, and sometimes criminal records — to confirm accuracy before finalizing employment.", whyItMatters: "It reduces hiring risk and is often a mandatory step for regulated industries like BFSI and healthcare." },
    { slug: "basic-salary", term: "Basic Salary", letter: "B", shortDef: "The fixed core component of an employee's pay, before allowances, bonuses, or deductions.", definition: "Basic salary is the fixed portion of compensation that forms the base for calculating other components like HRA, PF contributions, and gratuity. It typically does not vary month to month.", whyItMatters: "Because so many statutory calculations are based on basic salary, getting this component right is foundational to accurate payroll." },
    { slug: "bell-curve", term: "Bell Curve (Forced Ranking)", letter: "B", shortDef: "A performance rating method that distributes employees across predefined performance bands.", definition: "The bell curve, or forced ranking, is a relative performance evaluation method where employees are grouped into fixed proportions — e.g., top performers, average, and low performers — following a normal distribution curve.", whyItMatters: "It's a widely debated method in modern performance management, with many companies moving toward continuous feedback models instead." },
    { slug: "bonus", term: "Bonus", letter: "B", shortDef: "An additional payment made to employees, often tied to performance, tenure, or statutory requirement.", definition: "A bonus is compensation paid on top of regular salary — it can be discretionary (performance-linked) or statutory, as mandated under laws like the Payment of Bonus Act in India for eligible employees.", whyItMatters: "Statutory bonus calculations have specific eligibility and ceiling rules that payroll software needs to apply correctly." },

    // C
    { slug: "campus-recruitment", term: "Campus Recruitment", letter: "C", shortDef: "Hiring conducted directly at educational institutions to recruit students before or at graduation.", definition: "Campus recruitment refers to hiring drives organized on college or university campuses, where companies interview and make offers to graduating students, often for entry-level roles.", whyItMatters: "It's a major hiring channel for many industries and typically runs on its own separate recruitment calendar." },
    { slug: "career-break", term: "Career Break", letter: "C", shortDef: "An extended period where an employee steps away from the workforce, often for personal reasons.", definition: "A career break is a voluntary pause in employment — for reasons like caregiving, health, education, or travel — after which the individual may seek to re-enter the workforce.", whyItMatters: "Organizations increasingly build formal 'returnship' programs to support employees coming back after a career break." },
    { slug: "compensation-and-benefits", term: "Compensation and Benefits", letter: "C", shortDef: "The complete package of pay and non-pay rewards an employer offers, including salary, bonuses, and perks.", definition: "Compensation and benefits (C&B) covers everything an employee receives in exchange for their work — direct pay like salary and bonuses, and indirect benefits like insurance, leave, and retirement contributions.", whyItMatters: "A well-structured C&B strategy is one of the biggest levers for both attracting and retaining talent." },
    { slug: "compensatory-off", term: "Compensatory Off", letter: "C", shortDef: "Paid time off granted to an employee in exchange for working on a holiday or weekend.", definition: "Compensatory off (comp off) is leave awarded to employees who work on a designated off day or holiday, allowing them to take an equivalent day off later instead of, or in addition to, overtime pay.", whyItMatters: "Comp-off tracking needs to be tightly linked to attendance data to avoid over- or under-crediting employees." },
    { slug: "competency", term: "Competency", letter: "C", shortDef: "A measurable skill, behavior, or trait required to perform a job effectively.", definition: "A competency is a defined capability — technical, behavioral, or cognitive — that an organization expects employees to demonstrate in a given role, often used as the basis for hiring criteria and performance evaluation.", whyItMatters: "Competency frameworks give structure to hiring, appraisals, and learning & development programs alike." },
    { slug: "competency-based-pay", term: "Competency-Based Pay", letter: "C", shortDef: "A compensation model where pay increases are tied to the skills and competencies an employee develops.", definition: "Competency-based pay rewards employees for acquiring and demonstrating new skills or capabilities, rather than basing pay solely on tenure, role, or output.", whyItMatters: "It's often used alongside skill-matrix tracking to directly connect learning and development to compensation." },
    { slug: "consolidated-salary", term: "Consolidated Salary", letter: "C", shortDef: "A single fixed salary figure paid without a detailed breakup into separate components.", definition: "A consolidated salary is paid as one lump-sum amount rather than being split into components like basic, HRA, and allowances — common for contract or temporary roles.", whyItMatters: "Because there's no component-wise breakup, certain statutory benefits tied to specific components may not apply the same way." },

    // D
    { slug: "job-description", term: "Job Description", letter: "D", shortDef: "A written document outlining a role's responsibilities, requirements, and reporting structure.", definition: "A job description details what a role actually involves — duties, responsibilities, reporting lines, and expected outcomes — used both for hiring and for setting performance expectations.", whyItMatters: "It's distinct from a job specification, which focuses on the qualifications and traits a candidate needs, not the job itself.", related: ["job-specification"] },
    { slug: "job-specification", term: "Job Specification", letter: "D", shortDef: "The qualifications, skills, and experience required of a candidate for a specific role.", definition: "A job specification lists the minimum qualifications, experience, skills, and personal attributes a candidate must have to be considered for a role — complementing the job description, which defines the role itself.", whyItMatters: "Together, job description and job specification form the basis of an accurate, well-targeted job posting.", related: ["job-description"] },

    // E
    { slug: "e-recruitment", term: "E-Recruitment", letter: "E", shortDef: "The use of digital tools and online platforms to source, screen, and hire candidates.", definition: "E-recruitment refers to conducting the hiring process online — from posting jobs on job boards to screening resumes and conducting video interviews — as opposed to traditional, paper-based or in-person-only methods.", whyItMatters: "It's now the default hiring mode for most organizations, supported by ATS and job-board integrations." },
    { slug: "earned-leave", term: "Earned Leave", letter: "E", shortDef: "Paid leave accumulated by an employee based on time worked, which can usually be carried forward or encashed.", definition: "Earned leave (also called privilege leave) is leave that accrues over time as an employee works, and can typically be availed, carried forward to future years, or encashed subject to company policy.", whyItMatters: "Leave encashment on exit is calculated based on the earned leave balance, making accurate tracking essential during full-and-final settlement." },
    { slug: "employee-retention", term: "Employee Retention", letter: "E", shortDef: "An organization's ability to keep employees from leaving, especially high-performing ones.", definition: "Employee retention refers to the strategies and outcomes related to keeping employees engaged and employed at an organization over time, rather than losing them to attrition.", whyItMatters: "High attrition is expensive — retention data and exit-interview trends help HR teams catch problems before they compound." },
    { slug: "equity-theory", term: "Equity Theory", letter: "E", shortDef: "A motivation theory stating employees compare their input-to-output ratio with others to judge fairness.", definition: "Equity theory suggests employees assess fairness by comparing what they put into their job (effort, time, skill) against what they get out of it (pay, recognition), relative to their peers — and adjust motivation based on perceived imbalance.", whyItMatters: "It's a foundational idea behind why transparent, consistent compensation structures matter for morale." },
    { slug: "expatriate", term: "Expatriate", letter: "E", shortDef: "An employee working in a country other than their country of citizenship, usually on international assignment.", definition: "An expatriate (expat) is someone employed and residing in a foreign country, typically on a company-sponsored international assignment, with compensation and compliance needs that differ from local hires.", whyItMatters: "Expat payroll often involves additional tax treaty and compliance considerations across two countries." },

    // F
    { slug: "factor-comparison", term: "Factor Comparison", letter: "F", shortDef: "A job evaluation method that ranks roles based on compensable factors like skill and responsibility.", definition: "Factor comparison is a job evaluation technique where roles are compared and ranked against a set of common factors — such as skill, effort, responsibility, and working conditions — to determine relative pay levels.", whyItMatters: "It helps build internally consistent, defensible pay structures across different job families." },
    { slug: "five-factor-model", term: "Five-Factor Model", letter: "F", shortDef: "A widely used personality framework measuring openness, conscientiousness, extraversion, agreeableness, and neuroticism.", definition: "The Five-Factor Model (or 'Big Five') is a psychological framework used in some hiring and development contexts to assess personality traits along five core dimensions.", whyItMatters: "It's sometimes referenced in psychometric assessments used during recruitment or leadership development." },
    { slug: "fixed-pay", term: "Fixed Pay", letter: "F", shortDef: "The guaranteed portion of an employee's compensation, unaffected by performance or business results.", definition: "Fixed pay is the stable, predictable part of an employee's salary — including basic pay and standard allowances — as opposed to variable pay, which fluctuates with performance or company results.", whyItMatters: "The fixed-to-variable pay ratio is a key design choice in building competitive, motivating compensation structures.", related: ["variable-pay"] },
    { slug: "formal-communication", term: "Formal Communication", letter: "F", shortDef: "Official, structured communication that follows an organization's defined hierarchy and channels.", definition: "Formal communication flows through recognized organizational channels — official emails, memos, meetings, or HR announcements — following the company's structure and documentation standards.", whyItMatters: "It's contrasted with grapevine (informal) communication, and matters for HR when documenting policy changes or decisions." },
    { slug: "full-time-equivalent-fte", term: "Full-Time Equivalent (FTE)", letter: "F", shortDef: "A unit that standardizes part-time and full-time headcount into a comparable full-time measure.", definition: "FTE converts a mix of part-time and full-time employee hours into an equivalent number of full-time positions — for example, two employees each working half-time equal 1.0 FTE.", whyItMatters: "It's used in workforce planning and budgeting to get an accurate view of staffing levels beyond simple headcount." },
    { slug: "functional-job-analysis", term: "Functional Job Analysis", letter: "F", shortDef: "A method of analyzing a job by breaking down what the worker does with data, people, and things.", definition: "Functional Job Analysis (FJA) is a structured technique for describing a job in terms of the tasks performed and how the worker interacts with data, people, and physical things — used to write accurate job descriptions.", whyItMatters: "It provides a consistent, evidence-based foundation for job descriptions rather than relying on assumptions." },

    // G
    { slug: "generation-z", term: "Generation Z", letter: "G", shortDef: "The demographic cohort born roughly between the mid-1990s and early 2010s, now entering the workforce.", definition: "Generation Z refers to the cohort following Millennials, generally defined as those born from the mid-1990s to the early 2010s — a group HR teams study for shifting workplace expectations around flexibility, purpose, and technology.", whyItMatters: "Understanding generational differences informs how organizations design benefits, communication, and engagement strategies." },
    { slug: "grapevine-communication", term: "Grapevine Communication", letter: "G", shortDef: "Informal, unofficial communication that spreads through an organization outside formal channels.", definition: "Grapevine communication is the informal network through which information — accurate or not — spreads among employees outside of official channels, often faster than formal announcements.", whyItMatters: "Strong formal communication from HR helps reduce the spread of misinformation through the grapevine.", related: ["formal-communication"] },
    { slug: "gratuity", term: "Gratuity", letter: "G", shortDef: "A statutory lump-sum payment made to an employee upon leaving after a minimum period of continuous service.", definition: "Gratuity is a statutory benefit paid to employees in India who have completed at least five years of continuous service, calculated as a lump sum based on last drawn salary and years of service, payable on resignation, retirement, or termination.", whyItMatters: "Accurate gratuity calculation and trust management is a compliance requirement, not optional — errors here carry real legal risk." },
    { slug: "grievance", term: "Grievance", letter: "G", shortDef: "A formal complaint raised by an employee about a workplace issue, policy, or treatment.", definition: "A grievance is a formal expression of dissatisfaction by an employee regarding their employment — covering issues like unfair treatment, policy violations, or interpersonal conflict — typically handled through a defined grievance redressal process.", whyItMatters: "A structured, documented grievance process protects both employees and the organization, and is often a compliance requirement." },
    { slug: "group-dynamics", term: "Group Dynamics", letter: "G", shortDef: "The behavioral and psychological patterns that emerge within a team or group setting.", definition: "Group dynamics refers to how individuals within a team interact, influence one another, and collectively behave — a factor HR and managers consider when building and leading effective teams.", whyItMatters: "Understanding group dynamics helps in team design, conflict resolution, and improving collaboration." },

    // H
    { slug: "hr-analytics", term: "HR Analytics", letter: "H", shortDef: "The use of data analysis to inform HR decisions like hiring, retention, and performance.", definition: "HR analytics (or people analytics) applies data analysis techniques to workforce data — attendance, performance, attrition, and more — to uncover trends and support evidence-based HR decision-making.", whyItMatters: "It shifts HR from reactive administration to a strategic, data-informed function." },
    { slug: "hr-audit", term: "HR Audit", letter: "H", shortDef: "A systematic review of an organization's HR policies, processes, and compliance status.", definition: "An HR audit is a structured evaluation of HR practices — covering compliance, documentation, policy adherence, and process efficiency — to identify gaps and risks before they become bigger problems.", whyItMatters: "Regular audits catch compliance gaps early, which is far cheaper than dealing with penalties later." },
    { slug: "hr-benchmarking", term: "HR Benchmarking", letter: "H", shortDef: "Comparing an organization's HR metrics and practices against industry standards or competitors.", definition: "HR benchmarking involves measuring your organization's HR metrics — such as attrition rate, cost-per-hire, or compensation levels — against industry peers to identify where you stand and where to improve.", whyItMatters: "It helps HR leaders make a data-backed case for changes to compensation, policy, or headcount." },
    { slug: "hr-initiatives", term: "HR Initiatives", letter: "H", shortDef: "Planned programs or actions taken by HR to address a specific organizational goal or challenge.", definition: "HR initiatives are deliberate programs — such as a wellness program, diversity hiring push, or engagement survey — launched by HR to address a specific business or people challenge.", whyItMatters: "Well-tracked initiatives with clear metrics make it easier to demonstrate HR's impact on the business." },
    { slug: "human-capital-management", term: "Human Capital Management (HCM)", letter: "H", shortDef: "A strategic approach to managing an organization's workforce as a valuable business asset.", definition: "Human Capital Management is the broader strategic practice of recruiting, developing, and optimizing an organization's workforce — often used to describe integrated HR software suites that go beyond basic administration.", whyItMatters: "It frames HR as a value-driving function, not just a compliance and payroll department." },
    { slug: "human-resources-hr", term: "Human Resources (HR)", letter: "H", shortDef: "The organizational function responsible for managing the employee lifecycle, from hiring to exit.", definition: "Human Resources is the function within an organization responsible for recruiting, developing, compensating, and supporting employees throughout their time with the company, while also ensuring compliance with labor laws.", whyItMatters: "It's the foundational department this entire glossary — and HR Niti as a platform — exists to support." },

    // I
    { slug: "in-basket-technique", term: "In-Basket Technique", letter: "I", shortDef: "An assessment method simulating a manager's workload to evaluate decision-making and prioritization skills.", definition: "The in-basket technique is a simulation exercise, often used in assessment centers, where candidates handle a set of memos, emails, and tasks as if they were in a real managerial role — testing prioritization and decision-making.", whyItMatters: "It's used in leadership hiring and development programs to assess real-world judgment, not just interview answers." },
    { slug: "incentives", term: "Incentives", letter: "I", shortDef: "Rewards offered to motivate specific employee behavior or performance outcomes.", definition: "Incentives are additional rewards — monetary or otherwise — tied to achieving specific goals or performance thresholds, designed to motivate particular outcomes like sales targets or productivity gains.", whyItMatters: "Well-structured incentive schemes tied to accurate performance data drive the behavior they're designed for." },
    { slug: "informal-communication", term: "Informal Communication", letter: "I", shortDef: "Casual, unofficial communication between employees outside formal organizational channels.", definition: "Informal communication happens outside official channels — casual conversations, chat messages, or the office grapevine — and often carries information faster, if less reliably, than formal communication.", whyItMatters: "HR teams need to balance formal channels with an understanding of how information actually travels informally." },
    { slug: "internship", term: "Internship", letter: "I", shortDef: "A short-term, often structured work placement for students or early-career individuals to gain experience.", definition: "An internship is a temporary work arrangement, typically for students or recent graduates, offering practical work experience in exchange for a stipend or, in some cases, academic credit.", whyItMatters: "Internship programs are often a pipeline into full-time hiring and need their own onboarding and compliance handling." },
    { slug: "interview-panel", term: "Interview Panel", letter: "I", shortDef: "A group of interviewers who jointly assess a candidate during a single interview round.", definition: "An interview panel consists of multiple interviewers — often from different teams or seniority levels — who evaluate a candidate together, typically to reduce individual bias and get varied perspectives.", whyItMatters: "Panel interviews require coordinated scheduling and consolidated feedback, which recruitment software helps streamline." },

    // J
    { slug: "job-title", term: "Job Title", letter: "J", shortDef: "The formal name given to a specific role or position within an organization.", definition: "A job title is the designation assigned to a role, signaling its function and seniority level within the organization — used in org charts, payroll records, and external communication.", whyItMatters: "Consistent job titling matters for compensation benchmarking and building a clean organizational hierarchy." },
    { slug: "johari-window", term: "Johari Window", letter: "J", shortDef: "A model for understanding self-awareness by mapping known and unknown aspects of a person's behavior.", definition: "The Johari Window is a framework used in self-awareness and communication training, dividing personal traits into four quadrants based on what is known or unknown to oneself and to others.", whyItMatters: "It's a common tool in leadership development and team-building workshops." },

    // K
    { slug: "knowledge-transfer", term: "Knowledge Transfer", letter: "K", shortDef: "The process of sharing skills, information, and expertise from one employee to another.", definition: "Knowledge transfer is the structured process of passing on job-specific knowledge — often during offboarding, role transitions, or onboarding — to prevent institutional knowledge from being lost.", whyItMatters: "Poor knowledge transfer during exits is a common, avoidable source of operational disruption." },

    // L
    { slug: "labour-charges", term: "Labour Charges", letter: "L", shortDef: "Costs incurred by an employer for labor, including wages and statutory contributions.", definition: "Labour charges refer to the total cost an employer bears for labor — encompassing wages, statutory contributions like PF and ESI, and other employment-related costs.", whyItMatters: "Accurate labour cost tracking is essential for project costing and financial planning, especially in manufacturing and construction." },
    { slug: "layoff", term: "Layoff", letter: "L", shortDef: "The temporary or permanent termination of employees, usually due to business or economic reasons.", definition: "A layoff is the termination of employment initiated by the employer for reasons unrelated to individual performance — typically business downturns, restructuring, or redundancy — as opposed to a performance-based termination.", whyItMatters: "Layoffs carry specific statutory notice and compensation obligations that vary by jurisdiction and tenure." },
    { slug: "leave-travel-allowance-lta", term: "Leave Travel Allowance (LTA)", letter: "L", shortDef: "A tax-exempt allowance covering an employee's domestic travel expenses during leave.", definition: "LTA is a salary component in India that reimburses an employee's travel costs incurred while on leave, and is eligible for tax exemption under specific conditions defined by tax law.", whyItMatters: "Correct LTA configuration in payroll directly affects an employee's tax liability." },
    { slug: "leave-without-pay", term: "Leave Without Pay (LWP)", letter: "L", shortDef: "Leave taken by an employee when their paid leave balance is exhausted, resulting in a salary deduction.", definition: "Leave Without Pay is time off taken after an employee has exhausted their available paid leave balance, resulting in a proportional deduction from their salary for the period of absence.", whyItMatters: "LWP needs to be calculated precisely and reflected accurately in payroll to avoid disputes." },
    { slug: "loss-of-pay", term: "Loss of Pay (LOP)", letter: "L", shortDef: "A salary deduction applied when an employee is absent without approved, paid leave.", definition: "Loss of Pay refers to the salary reduction applied for days an employee was absent without a valid, approved leave — functionally similar to Leave Without Pay in most payroll systems.", whyItMatters: "LOP calculations need to tie directly to attendance records to stay accurate and defensible." },

    // M
    { slug: "management-by-objective", term: "Management By Objective (MBO)", letter: "M", shortDef: "A management approach where goals are jointly set by managers and employees to guide performance.", definition: "Management by Objective is a performance management approach where specific, measurable goals are collaboratively set between manager and employee, and performance is later evaluated against those agreed objectives.", whyItMatters: "It's a precursor to modern goal-setting frameworks like OKRs used in many performance management systems." },
    { slug: "mean-wage", term: "Mean Wage", letter: "M", shortDef: "The average wage earned across a defined group of employees or a specific role.", definition: "Mean wage is the statistical average salary calculated across a group — such as all employees in a role, department, or industry — often used in compensation benchmarking.", whyItMatters: "It's referenced when setting competitive pay bands relative to market data." },
    { slug: "merit-pay", term: "Merit Pay", letter: "M", shortDef: "A salary increase awarded to an employee based on individual performance rather than tenure alone.", definition: "Merit pay is a compensation increase tied directly to an employee's demonstrated performance, as opposed to automatic, tenure-based raises.", whyItMatters: "Linking merit pay to accurate, documented appraisal data keeps increment decisions defensible and fair." },
    { slug: "muster-roll", term: "Muster Roll", letter: "M", shortDef: "A statutory register recording employee attendance, often required under labor law for certain industries.", definition: "A muster roll is a formal attendance register that certain categories of employers, particularly in manufacturing and construction, are statutorily required to maintain, recording daily employee presence and wages.", whyItMatters: "Digital muster roll generation from attendance data simplifies a compliance requirement that's traditionally paper-based." },

    // N
    { slug: "nepotism", term: "Nepotism", letter: "N", shortDef: "Favoritism shown toward relatives or close associates in hiring or promotion decisions.", definition: "Nepotism refers to the practice of giving preferential treatment — in hiring, promotions, or assignments — to family members or close personal connections rather than based on merit.", whyItMatters: "Clear, documented hiring and promotion policies help organizations guard against nepotism and its impact on morale." },
    { slug: "notice-period", term: "Notice Period", letter: "N", shortDef: "The period an employee or employer must give before ending an employment contract.", definition: "A notice period is the length of time — commonly 30, 60, or 90 days — that either the employee or employer must provide as advance warning before employment officially ends, as defined in the employment contract.", whyItMatters: "Notice period tracking directly affects full-and-final settlement timing and exit workflows." },

    // O
    { slug: "on-roll-off-roll-payroll", term: "On-Roll / Off-Roll Payroll", letter: "O", shortDef: "A distinction between directly employed staff (on-roll) and those hired via a third party (off-roll).", definition: "On-roll employees are hired and paid directly by the company, appearing on its official payroll, while off-roll employees are engaged through a third-party contractor or staffing agency, even if working at the same location.", whyItMatters: "The distinction affects statutory obligations, benefits eligibility, and how payroll and compliance are managed for each group." },
    { slug: "onboarding", term: "Onboarding", letter: "O", shortDef: "The process of integrating a new employee into an organization, from paperwork to cultural orientation.", definition: "Onboarding covers everything involved in bringing a new hire up to speed — documentation, system access, training, introductions, and cultural orientation — typically spanning the first weeks or months of employment.", whyItMatters: "A structured, digital onboarding process directly affects how quickly a new hire becomes productive and how likely they are to stay." },
    { slug: "organizational-development", term: "Organizational Development (OD)", letter: "O", shortDef: "A planned, systematic effort to improve an organization's effectiveness through change management.", definition: "Organizational Development is a discipline focused on improving organizational effectiveness through planned interventions in culture, structure, and processes, often guided by behavioral science principles.", whyItMatters: "OD initiatives typically rely on accurate HR and engagement data to identify where change is needed." },
    { slug: "organizational-policies", term: "Organizational Policies", letter: "O", shortDef: "The formal rules and guidelines that govern employee conduct and organizational operations.", definition: "Organizational policies are the documented rules that govern everything from leave and attendance to code of conduct and expense claims, providing consistency in how situations are handled across the company.", whyItMatters: "Policies configured directly into HR software ensure they're applied consistently, not just filed away and forgotten." },

    // P
    { slug: "paid-holidays", term: "Paid Holidays", letter: "P", shortDef: "Designated public or company holidays for which employees receive regular pay without working.", definition: "Paid holidays are specific calendar days — national holidays, festivals, or company-declared days off — on which employees are compensated at their regular rate without being required to work.", whyItMatters: "Holiday calendars vary by state and religion in India, so HR systems need location-specific holiday lists." },
    { slug: "paid-time-off-pto", term: "Paid Time Off (PTO)", letter: "P", shortDef: "A pooled leave policy that combines vacation, sick, and personal leave into a single bank of days.", definition: "PTO is a leave policy model that consolidates different leave types — vacation, sick leave, personal days — into one flexible bank of days employees can use for any reason, rather than tracking each leave type separately.", whyItMatters: "PTO policies simplify leave administration but require careful configuration to still meet statutory sick-leave minimums." },
    { slug: "pay-band", term: "Pay Band", letter: "P", shortDef: "A defined salary range assigned to a specific role level or grade within an organization.", definition: "A pay band is a minimum-to-maximum salary range associated with a particular job level or grade, used to keep compensation consistent for similarly leveled roles across the organization.", whyItMatters: "Pay bands prevent salary decisions from being arbitrary and support pay equity across teams." },
    { slug: "pay-grade", term: "Pay Grade", letter: "P", shortDef: "A classification level used to group jobs of similar value or responsibility for compensation purposes.", definition: "A pay grade is a categorization that groups roles of comparable value, complexity, or responsibility together, typically each with its own associated pay band.", whyItMatters: "Grading structures form the backbone of a defensible, scalable compensation framework as a company grows." },
    { slug: "payroll-compliance", term: "Payroll Compliance", letter: "P", shortDef: "Adherence to all statutory laws and regulations governing employee pay, taxes, and deductions.", definition: "Payroll compliance means correctly calculating and remitting statutory obligations — PF, ESI, professional tax, TDS, and more — within required deadlines and formats set by law.", whyItMatters: "Non-compliance carries real financial and legal penalties, making this one of the highest-stakes parts of running payroll." },
    { slug: "payroll-service", term: "Payroll Service", letter: "P", shortDef: "A service — software or outsourced — that handles the calculation and processing of employee pay.", definition: "A payroll service refers to either software that automates payroll processing internally, or a third-party provider that manages payroll processing on a company's behalf, including statutory filings.", whyItMatters: "Choosing between software and outsourcing depends on team size, in-house expertise, and how much control you want over the process." },
    { slug: "payroll-settlement", term: "Payroll Settlement", letter: "P", shortDef: "The finalization of all dues owed to or by an employee, typically during exit.", definition: "Payroll settlement (often as part of full-and-final settlement) is the process of calculating and disbursing all outstanding dues — final salary, leave encashment, gratuity, and deductions — when an employee leaves the organization.", whyItMatters: "A slow or inaccurate settlement process is one of the most common sources of exit-related disputes." },
    { slug: "performance-development-plan-pdp", term: "Performance Development Plan (PDP)", letter: "P", shortDef: "A structured plan outlining specific actions to help an employee improve or grow in their role.", definition: "A Performance Development Plan is a documented, time-bound plan created collaboratively between manager and employee to address performance gaps or support skill growth, with specific milestones to track progress.", whyItMatters: "PDPs turn vague appraisal feedback into a concrete, trackable improvement path." },
    { slug: "perquisites", term: "Perquisites", letter: "P", shortDef: "Non-cash benefits provided to an employee in addition to salary, such as a company car or housing.", definition: "Perquisites (perks) are benefits-in-kind provided by an employer beyond cash salary — such as a company vehicle, accommodation, or club memberships — which may carry their own tax treatment.", whyItMatters: "Perquisites often have specific tax valuation rules that payroll systems need to apply correctly." },
    { slug: "probationary-period", term: "Probationary Period", letter: "P", shortDef: "An initial period of employment during which a new hire's fit and performance are evaluated.", definition: "The probationary period is a defined timeframe — commonly 3 to 6 months — at the start of employment during which both employer and employee can assess fit, often with different notice-period or termination terms than regular employment.", whyItMatters: "Systems need to track probation end dates to trigger confirmation reviews on time." },

    // Q
    { slug: "quality-of-work-life-qwl", term: "Quality of Work Life (QWL)", letter: "Q", shortDef: "A measure of how favorable or unfavorable an employee's overall work environment is to their well-being.", definition: "Quality of Work Life refers to the overall favorability of an employee's working conditions — covering factors like work-life balance, job security, workplace relationships, and growth opportunities.", whyItMatters: "QWL is increasingly tracked via engagement surveys as a leading indicator of retention risk." },

    // R
    { slug: "recruitment", term: "Recruitment", letter: "R", shortDef: "The end-to-end process of identifying, attracting, and hiring candidates to fill open roles.", definition: "Recruitment covers the full hiring process — from defining a role and sourcing candidates, to screening, interviewing, and making an offer — aimed at filling open positions with suitable talent.", whyItMatters: "It's the entry point to the entire employee lifecycle, making its efficiency foundational to workforce planning." },
    { slug: "reimbursement", term: "Reimbursement", letter: "R", shortDef: "Repayment to an employee for approved business expenses paid out of their own pocket.", definition: "Reimbursement is the process of compensating an employee for legitimate business expenses — travel, meals, supplies — that they initially paid for themselves, typically after submitting proof and approval.", whyItMatters: "A digital expense and reimbursement workflow speeds up what's traditionally a slow, paperwork-heavy process." },
    { slug: "remuneration", term: "Remuneration", letter: "R", shortDef: "The total compensation an employee receives for their work, including salary and other benefits.", definition: "Remuneration is a broad term covering all forms of compensation an employee receives — salary, bonuses, allowances, and benefits — in exchange for their services.", whyItMatters: "It's often used interchangeably with 'compensation' in policy and legal documentation." },
    { slug: "requisition", term: "Requisition", letter: "R", shortDef: "A formal request raised to initiate the hiring process for a new or replacement position.", definition: "A job requisition is the formal internal request — usually requiring budget and headcount approval — that authorizes recruitment to begin sourcing candidates for a specific role.", whyItMatters: "Tracking requisitions properly prevents unauthorized or unbudgeted hiring." },
    { slug: "restricted-holidays", term: "Restricted Holidays", letter: "R", shortDef: "Optional holidays employees can choose from a list, typically tied to regional or religious observances.", definition: "Restricted holidays are a set of optional holidays — often religious or regional festivals — from which employees can select a limited number to take as paid leave, based on personal preference.", whyItMatters: "Configurable restricted holiday policies help accommodate India's culturally diverse workforce fairly." },
    { slug: "retrenchment", term: "Retrenchment", letter: "R", shortDef: "The termination of employment due to surplus staffing, typically for economic or operational reasons.", definition: "Retrenchment is the formal termination of employees due to workforce surplus — driven by cost-cutting, automation, or restructuring — and is governed by specific statutory notice and compensation requirements in India.", whyItMatters: "Retrenchment has stricter legal obligations than a standard resignation-driven exit, and getting the process wrong carries real risk." },
    { slug: "rewards-and-recognition", term: "Rewards and Recognition", letter: "R", shortDef: "Programs designed to acknowledge and reward employees for their contributions and achievements.", definition: "Rewards and Recognition (R&R) programs are structured initiatives — award ceremonies, spot bonuses, shoutouts — designed to formally acknowledge employee contributions and reinforce desired behaviors.", whyItMatters: "Consistent R&R programs are strongly linked to higher engagement and lower attrition." },

    // S
    { slug: "sabbatical-leave", term: "Sabbatical Leave", letter: "S", shortDef: "An extended, often unpaid leave granted to an employee, typically for personal growth or study.", definition: "Sabbatical leave is a long-term leave of absence — sometimes paid, often not — granted to long-tenured employees for purposes like further study, travel, or personal projects, with an agreement to return.", whyItMatters: "Offering sabbaticals can be a differentiator in retaining senior talent looking for flexibility." },
    { slug: "salaried-employee", term: "Salaried Employee", letter: "S", shortDef: "An employee paid a fixed, regular salary rather than being paid by the hour.", definition: "A salaried employee receives a fixed, predetermined amount of pay on a regular schedule (monthly, typically), regardless of the exact number of hours worked in a given period — as opposed to hourly or daily-wage workers.", whyItMatters: "Salaried vs. hourly classification affects how overtime, leave, and statutory benefits are calculated." },
    { slug: "salary-breakup", term: "Salary Breakup", letter: "S", shortDef: "The detailed division of an employee's total compensation into individual components.", definition: "A salary breakup (or salary structure) shows how an employee's total CTC is divided into specific components — basic, HRA, allowances, and deductions — each of which may have different tax and compliance implications.", whyItMatters: "A well-designed salary breakup can meaningfully improve an employee's take-home pay through tax-efficient structuring." },
    { slug: "sensitivity-training", term: "Sensitivity Training", letter: "S", shortDef: "Training designed to increase employee awareness of biases, diversity, and workplace conduct.", definition: "Sensitivity training is a workplace training program aimed at increasing awareness of unconscious bias, cultural differences, and appropriate workplace behavior, often as part of diversity and inclusion or POSH compliance initiatives.", whyItMatters: "It's frequently a compliance requirement, particularly around workplace harassment prevention laws in India." },
    { slug: "shrinkage", term: "Shrinkage", letter: "S", shortDef: "The gap between scheduled and actually available working time, due to leave, training, or absence.", definition: "Shrinkage, common in workforce planning for operations-heavy teams, refers to the percentage of scheduled work time lost to leave, breaks, training, or absenteeism — reducing effective available capacity.", whyItMatters: "Accurate shrinkage data is essential for realistic staffing and scheduling in shift-based operations." },
    { slug: "staffing", term: "Staffing", letter: "S", shortDef: "The broader HR function of ensuring an organization has the right people in the right roles.", definition: "Staffing encompasses workforce planning, recruitment, and placement — the ongoing function of ensuring the organization has the right number of people with the right skills in the right roles.", whyItMatters: "It's a strategic planning function that sits above day-to-day recruitment execution." },
    { slug: "stipend", term: "Stipend", letter: "S", shortDef: "A fixed, often modest payment made to interns, trainees, or apprentices instead of a full salary.", definition: "A stipend is a set periodic payment given to someone in a training or learning capacity — such as interns or apprentices — typically lower than a full employee salary and structured differently for tax purposes.", whyItMatters: "Stipends need to be tracked and taxed differently from regular salary in payroll systems." },
    { slug: "subordinate", term: "Subordinate", letter: "S", shortDef: "An employee who reports to and works under the direction of a more senior team member.", definition: "A subordinate is an employee positioned below another in the organizational hierarchy, reporting to and taking direction from that senior team member or manager.", whyItMatters: "Reporting structures defined in an HRMS directly drive approval workflows for leave, expenses, and appraisals." },
    { slug: "suspension", term: "Suspension", letter: "S", shortDef: "A temporary removal of an employee from active duty, usually pending investigation or as discipline.", definition: "Suspension is a temporary measure where an employee is barred from performing their duties — sometimes with pay, sometimes without — typically while a disciplinary investigation is underway.", whyItMatters: "Suspension needs to be documented carefully, as it directly affects payroll status and is often legally sensitive." },

    // T
    { slug: "talent-acquisition", term: "Talent Acquisition", letter: "T", shortDef: "The strategic, longer-term process of identifying and attracting skilled people, beyond just filling open roles.", definition: "Talent acquisition is a strategic approach to hiring that focuses on long-term workforce planning, employer branding, and building talent pipelines — broader in scope than reactive, role-by-role recruitment.", whyItMatters: "It's the difference between hiring only when a role opens and proactively building a pipeline of future talent." },
    { slug: "total-quality-management", term: "Total Quality Management (TQM)", letter: "T", shortDef: "A management approach focused on continuous improvement across all organizational processes.", definition: "Total Quality Management is a management philosophy centered on continuous improvement, employee involvement, and customer focus across every process in an organization, not just manufacturing quality control.", whyItMatters: "TQM principles influence how some organizations structure performance and process-improvement initiatives." },
    { slug: "transformational-leadership", term: "Transformational Leadership", letter: "T", shortDef: "A leadership style that inspires and motivates employees toward a shared vision beyond self-interest.", definition: "Transformational leadership is a style where leaders inspire and motivate their teams toward a larger vision, fostering innovation and engagement, as opposed to purely transactional, task-focused management.", whyItMatters: "It's a common framework referenced in leadership development and management training programs." },

    // U
    { slug: "unemployment", term: "Unemployment", letter: "U", shortDef: "The state of being without paid work while actively seeking employment.", definition: "Unemployment refers to individuals who are without a job but are actively seeking and available for work — a macroeconomic indicator that also affects hiring market conditions.", whyItMatters: "Labor market conditions influence how competitive recruitment and retention strategies need to be." },
    { slug: "unpaid-leave", term: "Unpaid Leave", letter: "U", shortDef: "Time off from work during which an employee does not receive regular pay.", definition: "Unpaid leave is a period of approved absence during which the employee does not receive their regular salary, typically granted after paid leave balances are exhausted or for extended personal reasons.", whyItMatters: "It needs to be clearly distinguished from unapproved absence in both policy and payroll systems." },

    // V
    { slug: "variable-pay", term: "Variable Pay", letter: "V", shortDef: "The portion of compensation that fluctuates based on individual, team, or company performance.", definition: "Variable pay is compensation that isn't fixed — bonuses, commissions, or incentive payouts — tied to performance metrics at the individual, team, or organizational level.", whyItMatters: "The right fixed-to-variable pay mix balances stability for employees with performance motivation for the business.", related: ["fixed-pay"] },
    { slug: "vestibule-training", term: "Vestibule Training", letter: "V", shortDef: "Training conducted in a simulated work environment separate from the actual job floor.", definition: "Vestibule training takes place in a dedicated training area that mimics the actual work environment, allowing new employees to practice skills without the risk or disruption of doing so on the live production floor.", whyItMatters: "It's especially relevant in manufacturing and technical roles where mistakes on the live floor carry real cost or risk." },
    { slug: "voluntary-time-off-vto", term: "Voluntary Time Off (VTO)", letter: "V", shortDef: "An option for employees to voluntarily take unpaid time off, often during periods of low business demand.", definition: "VTO allows employees to opt into taking unpaid time off, typically offered by employers during periods of reduced business demand as an alternative to mandatory layoffs or reduced hours.", whyItMatters: "It gives operations-heavy businesses a flexible lever to manage costs without resorting to job cuts." },

    // W
    { slug: "weekly-off", term: "Weekly Off", letter: "W", shortDef: "A designated day each week on which an employee is not required to work, with pay.", definition: "A weekly off is the statutorily mandated day (or days) each week during which an employee is not required to work while still receiving regular pay, distinct from public holidays.", whyItMatters: "Weekly-off rules directly affect overtime calculations when employees are asked to work on their designated off day." },
    { slug: "work-ethics", term: "Work Ethics", letter: "W", shortDef: "The set of moral principles and standards guiding professional behavior in the workplace.", definition: "Work ethics refers to the values and standards — integrity, accountability, respect, professionalism — that guide how employees are expected to conduct themselves at work.", whyItMatters: "Codes of conduct built on clear work-ethic principles form the basis of most disciplinary and grievance policies." },
    { slug: "workplace-retaliation", term: "Workplace Retaliation", letter: "W", shortDef: "Adverse action taken against an employee for reporting misconduct or exercising a legal right.", definition: "Workplace retaliation occurs when an employer takes negative action — demotion, termination, exclusion — against an employee because they reported misconduct, filed a complaint, or exercised a legally protected right.", whyItMatters: "Protecting against retaliation is essential for grievance and whistleblower processes to actually function." },
    { slug: "wrongful-termination", term: "Wrongful Termination", letter: "W", shortDef: "The unlawful dismissal of an employee in violation of contract terms or statutory protections.", definition: "Wrongful termination refers to firing an employee in a way that violates their employment contract, statutory notice requirements, or other legal protections against unfair dismissal.", whyItMatters: "Clear, documented performance and disciplinary records in HR systems help protect organizations from wrongful termination claims." },

    // Additional high-search-volume terms (modern workplace vocabulary + common
    // acronyms). Curated rather than exhaustive — see conversation note on scope.
    { slug: "attrition-rate", term: "Attrition Rate", letter: "A", shortDef: "The percentage of employees who leave an organization over a given period.", definition: "Attrition rate measures the proportion of employees who exit a company — voluntarily or involuntarily — over a specific timeframe, usually calculated monthly or annually as a percentage of total headcount.", whyItMatters: "It's one of the most-watched HR metrics, since rising attrition is often the earliest signal of deeper engagement or compensation problems.", related: ["employee-retention"] },
    { slug: "boomerang-employee", term: "Boomerang Employee", letter: "B", shortDef: "A former employee who leaves an organization and is later rehired.", definition: "A boomerang employee is someone who resigns or is let go, but later returns to work for the same organization — often bringing new skills or perspective gained elsewhere.", whyItMatters: "Many companies now formally track and re-engage strong past employees as a lower-risk hiring pipeline." },
    { slug: "burnout", term: "Burnout", letter: "B", shortDef: "A state of physical and emotional exhaustion caused by prolonged, excessive work stress.", definition: "Burnout is a syndrome resulting from chronic, unmanaged workplace stress, characterized by exhaustion, cynicism toward one's job, and reduced professional effectiveness.", whyItMatters: "Recognized by the WHO as an occupational phenomenon, burnout is now a standard factor tracked in employee wellbeing and engagement surveys." },
    { slug: "career-cushioning", term: "Career Cushioning", letter: "C", shortDef: "The practice of quietly preparing backup job options while still employed, in case of layoffs.", definition: "Career cushioning describes employees passively job-searching, networking, or upskilling while still in their current role, as a hedge against potential layoffs or job insecurity.", whyItMatters: "Rising career cushioning in a team can be an early signal of low confidence in job security worth addressing." },
    { slug: "coffee-badging", term: "Coffee Badging", letter: "C", shortDef: "Briefly showing up to the office to satisfy an in-office mandate before leaving to work remotely.", definition: "Coffee badging refers to employees making a brief physical appearance at the office — just long enough to badge in — before leaving to work from home for the rest of the day.", whyItMatters: "It's become a common workaround to strict return-to-office mandates and a signal that hybrid policy design needs rethinking." },
    { slug: "ctc-cost-to-company", term: "CTC (Cost to Company)", letter: "C", shortDef: "The total amount a company spends on an employee annually, including salary and all benefits.", definition: "CTC represents the full cost an employer incurs for an employee in a year — base salary, allowances, bonuses, employer PF contribution, insurance, and other benefits combined — not just the take-home pay the employee receives.", whyItMatters: "Because take-home pay is always lower than CTC, clearly explaining the breakup to candidates and employees prevents confusion and disputes." },
    { slug: "employee-value-proposition-evp", term: "Employee Value Proposition (EVP)", letter: "E", shortDef: "The unique set of benefits and value an employer offers in exchange for an employee's skills and commitment.", definition: "An Employee Value Proposition is the combination of compensation, culture, growth opportunities, and benefits that defines what an organization offers employees in return for their contribution — essentially, the employer's answer to 'why work here?'", whyItMatters: "A clear EVP is central to employer branding and directly affects both recruitment conversion and retention." },
    { slug: "employer-brand", term: "Employer Brand", letter: "E", shortDef: "An organization's reputation and image as an employer, as perceived by current and prospective employees.", definition: "Employer brand is how a company is perceived as a place to work — shaped by employee reviews, culture, compensation, and public reputation — distinct from its brand as a product or service provider.", whyItMatters: "A strong employer brand lowers cost-per-hire and improves the quality of inbound candidates." },
    { slug: "esop-employee-stock-ownership-plan", term: "ESOP (Employee Stock Ownership Plan)", letter: "E", shortDef: "A benefit plan giving employees ownership interest in the company through stock or stock options.", definition: "An ESOP grants employees equity or options to purchase equity in the company they work for, usually vesting over a defined period, aligning employee incentives with long-term company performance.", whyItMatters: "ESOP grants and vesting schedules need to be tracked carefully alongside standard compensation and payroll records." },
    { slug: "fobo-fear-of-being-obsolete", term: "FOBO (Fear of Being Obsolete)", letter: "F", shortDef: "Employee anxiety about being replaced by automation, AI, or evolving skill requirements.", definition: "FOBO describes the growing workplace anxiety among employees about their skills becoming outdated due to automation, AI, or rapidly shifting job requirements.", whyItMatters: "It's increasingly relevant to L&D strategy, as addressing FOBO through reskilling programs can directly reduce attrition risk." },
    { slug: "ghost-jobs", term: "Ghost Jobs", letter: "G", shortDef: "Job postings that remain listed and open despite the company not actively hiring for the role.", definition: "Ghost jobs are job listings that stay posted — sometimes for months — even though the employer isn't actively interviewing or intends to fill the position, whether to gauge market interest, build a talent pipeline, or by administrative oversight.", whyItMatters: "Keeping job postings accurate and closing filled or cancelled roles promptly protects candidate trust and employer brand." },
    { slug: "glass-ceiling", term: "Glass Ceiling", letter: "G", shortDef: "An invisible, unofficial barrier that prevents certain groups from advancing to senior leadership roles.", definition: "The glass ceiling refers to an unacknowledged barrier — often affecting women and underrepresented groups — that limits advancement to senior or executive positions despite qualifications and performance.", whyItMatters: "Tracking promotion and leadership representation data helps organizations identify and address glass-ceiling patterns." },
    { slug: "great-resignation", term: "Great Resignation", letter: "G", shortDef: "The global wave of mass voluntary employee resignations that peaked in 2021-2022.", definition: "The Great Resignation refers to the historically high rate of voluntary employee resignations seen globally in the aftermath of the COVID-19 pandemic, driven by shifting priorities around flexibility, pay, and purpose.", whyItMatters: "It permanently changed how organizations think about retention, flexibility, and compensation benchmarking." },
    { slug: "job-hopping", term: "Job Hopping", letter: "J", shortDef: "The practice of frequently changing jobs, typically staying at each for a relatively short period.", definition: "Job hopping describes a pattern of moving between employers every one to two years, often to accelerate salary growth or skill acquisition faster than internal promotion allows.", whyItMatters: "Understanding why employees job-hop — often compensation stagnation — helps shape more competitive retention strategy." },
    { slug: "job-satisfaction", term: "Job Satisfaction", letter: "J", shortDef: "The degree to which an employee feels content, fulfilled, and positive about their job.", definition: "Job satisfaction measures how positively an employee feels about their role, encompassing factors like work content, compensation, relationships, and growth opportunities.", whyItMatters: "It's a leading indicator tracked through engagement surveys, strongly correlated with both productivity and retention." },
    { slug: "kpi-key-performance-indicator", term: "KPI (Key Performance Indicator)", letter: "K", shortDef: "A measurable value used to track how effectively an individual or organization is achieving key objectives.", definition: "A KPI is a specific, quantifiable metric — such as attrition rate or time-to-hire in HR contexts — used to evaluate progress against a defined goal or objective.", whyItMatters: "Well-chosen HR KPIs turn vague goals like 'improve retention' into something trackable and actionable." },
    { slug: "moonlighting", term: "Moonlighting", letter: "M", shortDef: "Taking on a second job or freelance work, often without an employer's knowledge, alongside a primary job.", definition: "Moonlighting refers to an employee working a second job — frequently freelance or remote — in addition to their primary employment, sometimes without disclosing it to their main employer.", whyItMatters: "It's a growing policy consideration for HR teams, particularly around conflict-of-interest and confidentiality clauses." },
    { slug: "quiet-quitting", term: "Quiet Quitting", letter: "Q", shortDef: "Doing only the minimum required by a job description, without going above and beyond.", definition: "Quiet quitting describes employees who stop going beyond their formal job requirements — declining extra hours or discretionary effort — while remaining formally employed, rather than actually resigning.", whyItMatters: "It's often a symptom of disengagement, making it a key term in modern engagement-survey analysis." },
    { slug: "quiet-firing", term: "Quiet Firing", letter: "Q", shortDef: "An employer's practice of making conditions unfavorable to indirectly push an employee to resign.", definition: "Quiet firing describes an employer indirectly pushing an employee toward resignation — through neglect, reduced responsibilities, or a hostile environment — rather than initiating a formal, direct termination.", whyItMatters: "It's a practice HR should actively guard against, since it carries reputational and potential legal risk compared to a transparent exit process." },
    { slug: "rage-apply", term: "Rage Apply", letter: "R", shortDef: "Impulsively applying to multiple jobs in a burst of frustration with one's current employer.", definition: "Rage applying refers to an employee, in a moment of workplace frustration, quickly submitting applications to several other jobs — a reactive rather than planned job search.", whyItMatters: "A spike in this behavior across a team often points to an underlying management or culture issue worth investigating." },
    { slug: "revenge-quitting", term: "Revenge Quitting", letter: "R", shortDef: "Resigning abruptly and dramatically as a form of protest against poor treatment at work.", definition: "Revenge quitting is when an employee resigns suddenly and publicly — sometimes without notice — as a direct reaction to feeling mistreated, overlooked, or undervalued by their employer.", whyItMatters: "It underscores why proactive grievance handling and exit interviews matter — by the time it happens, the relationship is usually unsalvageable." },
    { slug: "resenteeism", term: "Resenteeism", letter: "R", shortDef: "Staying in a job while feeling resentful and disengaged, rather than leaving.", definition: "Resenteeism describes employees who remain in their roles — often due to financial necessity or a weak job market — while feeling unhappy and disengaged, effectively 'quiet quitting' out of resentment rather than choice.", whyItMatters: "It's a harder retention risk to spot than attrition, since the employee isn't leaving — engagement data is key to catching it." },
    { slug: "saas-software-as-a-service", term: "SaaS (Software as a Service)", letter: "S", shortDef: "A software delivery model where applications are hosted in the cloud and accessed via the internet.", definition: "SaaS is a software distribution model where applications — like modern HRMS platforms — are hosted centrally by the provider and accessed by users over the internet, typically via subscription, rather than installed locally.", whyItMatters: "It's the delivery model HR Niti itself is built on, enabling updates and access from anywhere without on-premise infrastructure." },
    { slug: "six-sigma", term: "Six Sigma", letter: "S", shortDef: "A data-driven methodology for eliminating defects and improving process quality.", definition: "Six Sigma is a set of techniques and tools for process improvement, aiming to reduce variation and defects to a statistically near-zero rate — occasionally applied to HR processes like onboarding or payroll accuracy.", whyItMatters: "It's referenced when organizations apply rigorous process-improvement thinking to HR operations, not just manufacturing." },
    { slug: "unconscious-bias", term: "Unconscious Bias", letter: "U", shortDef: "Automatic, unintentional judgments or stereotypes that influence decisions without conscious awareness.", definition: "Unconscious bias refers to implicit attitudes or stereotypes that affect our understanding, actions, and decisions — including in hiring, performance reviews, and promotions — without the person being consciously aware of it.", whyItMatters: "Structured, criteria-based hiring and review processes are one of the most effective tools for reducing its impact." },
    { slug: "whistleblower", term: "Whistleblower", letter: "W", shortDef: "An individual who reports misconduct, illegal activity, or policy violations within an organization.", definition: "A whistleblower is an employee or insider who reports wrongdoing — fraud, harassment, safety violations, or other misconduct — either internally or to an external authority.", whyItMatters: "Protecting whistleblowers from retaliation is essential for internal reporting mechanisms to actually surface problems.", related: ["workplace-retaliation"] },
    { slug: "work-life-balance", term: "Work-Life Balance", letter: "W", shortDef: "The equilibrium between an employee's professional responsibilities and personal life.", definition: "Work-life balance refers to how well an employee is able to manage the demands of their job alongside personal, family, and health priorities, without one consistently overwhelming the other.", whyItMatters: "It's consistently one of the top factors candidates and employees cite when evaluating whether to join or stay at a company." },
];

export const glossaryLetters = Array.from(
    new Set(glossaryTerms.map((t) => t.letter))
).sort((a, b) => (a === "#" ? -1 : b === "#" ? 1 : a.localeCompare(b)));
